### ISSUE TITLE
[ReminderList] NullPointerException when initialising ReminderListWindow

### ISSUE THREAD

**Issue by c0j0s** [AY2223S2-CS2103-F11-2/tp#94]
**Potential issue:**
Missing mapping fxid for reminderList in fxml

**Error:**
```
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at seedu.address.ui.UiPart.getFxmlFileUrl(UiPart.java:65)
        at seedu.address.ui.UiPart.<init>(UiPart.java:55)
        at seedu.address.ui.ReminderListWindow.<init>(ReminderListWindow.java:31)
        at seedu.address.ui.MainWindow.<init>(MainWindow.java:92)
        at seedu.address.ui.UiManager.start(UiManager.java:43)
        at seedu.address.MainApp.start(MainApp.java:205)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by ChinJunAn** [comment]
I just pulled from master, everything is working fine on my end. May I check how you get this error? The fxml file for ReminderListWindow exist.

**Comment by c0j0s** [comment]
hmm... it works fine now.
